### ISSUE TITLE
Webperf: Webfonts load slow

### ISSUE THREAD

**Issue by Munter** [npm/www#363]
On all pages that use common.css there is a very slow critical loading path for the google webfonts that allow usage of 'Source Sans Pro'.

The critical path goes:
- index.html
- common.css `@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600);`
- https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600
- font files

You can see from the [connection view](https://www.webpagetest.org/result/180330_EW_cbad4538b5b1d1bbe428b78cab8b64ab/1/breakdown/) that google font css isn't even downloaded before the entire common.css has loaded.

Suggestions to speed up this critical path:

## Move google fonts CSS from common.css to html template head

The download of the google font css will start in parallel with the other css files, thus skipping the latency and bandwidth delay of common.css

## Preload and preconnect

Preload the google fonts CSS and prewarm the connection to the google fonts webfont server in order to kick off downloads as soon as possible and not suffer from the latency of establishing a secure connection once the font downloads start triggering.

Preferably use an HTTP link header:

```
link: <https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600>; rel=preload; as=style; crossorigin=anonymous, <https://fonts.gstatic.com>; rel=preconnect; as=style; crossorigin=anonymous
```

or with html-tags:

```html
<link rel="preload" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600" as="style" crossorigin>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
```

## Self-host web fonts

The google fonts are downloaded over two critical requests, which are on different servers. This means there's a high cost of dns lookup, tls handshake and tcp slowstart on both the CSS and the fonts from google. A http2 connection, like static.npmjs.com has, can outperform googles serving of webfonts if it is also properly CDN distributed.

Upsides:
- Immediate download from an already warmed up connection
- Ability to preload font files with known names
- Ability to add `font-display` CSS property in `@font-face` declaration block, for improved control over how font rendering should work

Downsides:
- More work to fetch the font files and construct the `@font-face` block (one time investment)
- Potentially causes larger downloads for browser that would otherwise download only a relevant subset. Google serves css with unicode-ranged subsets for capable browsers, which means the payload per file is smaller. In my experience the lower latency stalls usually win you more than the download time increases

Suggestion for a `@font-face` block:

```CSS
@font-face {
  font-family: 'Source Sans Pro';
  font-display: swap;
  font-style: normal;
  font-weight: 300;
  src: local('Source Sans Pro Light')
     , local('SourceSansPro-Light')
     , url(/path/to/SourceSansPro-Light.woff2) format("woff2")
     , url(/path/to/SourceSansPro-Light.woff) format("woff");
}

@font-face {
  font-family: 'Source Sans Pro';
  font-display: swap;
  font-style: normal;
  font-weight: 400;
  src: local('Source Sans Pro Regular')
     , local('SourceSansPro-Regular')
     , url(/path/to/SourceSansPro-Regular.woff2) format("woff2")
     , url(/path/to/SourceSansPro-Regular.woff) format("woff");
}

@font-face {
  font-family: 'Source Sans Pro';
  font-display: swap;
  font-style: normal;
  font-weight: 600;
  src: local('Source Sans Pro SemiBold')
     , local('SourceSansPro-SemiBold')
     , url(/path/to/SourceSansPro-SemiBold.woff2) format("woff2")
     , url(/path/to/SourceSansPro-SemiBold.woff) format("woff");
}
```

If you choose to do this one, adding preload hints directly to the fonts is a must. That's where all the speed gains from side stepping the critical request chains happen.
